### ISSUE TITLE
server.sh services  restart seems to destroy volumes

### ISSUE THREAD

**Issue by bayeslearnerold** [borjapazr/mars-server#1]
I am not sure why, but restart target of a service seems to be destroying volumes, instead of just stop and start. 

By the way, there are many projects out there including homelabos, charjabox, make-my-server, ansible-nas-master, homeserver-compose and many more.  Your little creation is so simple and yet concise.

**Comment by borjapazr** [comment]
Hi @bayeslearner !

Thank you for reporting the problem. It should be fixed by now.

I hope you find this little tool useful. It's very simple as you say, but personally it helps me to deploy very easily and quickly personal projects and other self-hosted tools.

Cheers 🍻
